# Generated by Django 4.2.3 on 2025-02-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('fatherName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('pcbpercentage', models.FloatField()),
                ('neetScore', models.FloatField()),
                ('course', models.CharField(choices=[('B.H.M.S', 'B.H.M.S')], max_length=255)),
                ('reason', models.TextField()),
            ],
        ),
    ]
