# Generated by Django 4.2.3 on 2025-02-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('fatherName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contactNo', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
