# Generated by Django 4.2.3 on 2025-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='course',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(max_length=255),
        ),
    ]
