# Generated by Django 4.2.3 on 2025-02-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_enquiry_course_alter_enquiry_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='dob',
            field=models.CharField(max_length=255),
        ),
    ]
