# Generated by Django 5.1.6 on 2025-02-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_enquiry_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='reason',
        ),
    ]
