# Generated by Django 5.1.6 on 2025-02-18 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_meta_description_category_meta_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='meta_title',
        ),
    ]
