# Generated by Django 5.1.6 on 2025-02-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_category_slug_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
