# Generated by Django 5.1.6 on 2025-02-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_image_gallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
