# Generated by Django 5.1.6 on 2025-02-14 05:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_content_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=tinymce.models.HTMLField(),
        ),
    ]
